
baseurl: "/jekyll_blog"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 4
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]



