# Site settings
title: Aakash's Blog
header-img: img/home-bg.jpg
email: aakashkumar5069@gmail.com
description: "Rolling into Jekyll !"
baseurl: "/jekyll_blog"
github_username: aakashkumar5069
facebook_username: profile.php?id=100007596105533
email_username:  aakashkumar5069@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 4
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]

plugins: - jekyll-sitemap



